export const GRATITUDE_PROMPTS = [
  "What's something that made you smile today?",
  "Who is someone you're thankful for and why?",
  "What's a small pleasure you enjoyed recently?",
  "What's an accomplishment you're proud of this week?",
  "What's something beautiful you saw or experienced lately?",
  "What's a challenge you overcame recently that you're grateful for?",
  "What's a skill or ability you have that you're thankful for?",
  "What's something in nature that you appreciate?",
  "What's a piece of technology that makes your life easier?",
  "What's a book, movie, or song that you're grateful for and why?",
  "What's a memory that always makes you feel grateful when you think about it?",
  "What's something you're looking forward to?",
  "What's a lesson you learned recently that you're thankful for?",
  "What's something about your home that you appreciate?",
  "Who's someone that taught you something valuable?",
  "What is one good thing that I often take for granted?",
  "Who do I need to thank?",
  "What are three things I'm grateful for, no matter how small?",
  "Describe your favorite moment of each part of the day.",
  "Think of a time when you were really brave. What do you most appreciate about that experience?",
  "What do you appreciate about your body?",
  "What makes you feel confident?",
  "When do you feel most supported in life?",
  "What was the most perfect moment of your life?",
  "What energizes you?",
  "Who inspires you? Why?",
  "What motivates you?",
  "What are you most interested in?",
  "What does it mean to thrive? When have you thrived?",
  "What are some of your favorite traditions?",
];
