export const GRATITUDE_PROMPTS = [
  "What's something that made you smile today?",
  "Who is someone you're thankful for and why?",
  "What's a small pleasure you enjoyed recently?",
  "What's an accomplishment you're proud of this week?",
  "What's something beautiful you saw or experienced lately?",
  "What's a challenge you overcame recently that you're grateful for?",
  "What's a skill or ability you have that you're thankful for?",
  "What's something in nature that you appreciate?",
  "What's a piece of technology that makes your life easier?",
  "What's a book, movie, or song that you're grateful for and why?",
  "What's a memory that always makes you feel grateful when you think about it?",
  "What's something you're looking forward to?",
  "What's a lesson you learned recently that you're thankful for?",
  "What's something about your home that you appreciate?",
  "Who's someone that taught you something valuable?",
];
